### ISSUE TITLE
Timeouts on Heroku

### ISSUE THREAD

**Issue by srbiv** [jamesward/salesforce-webhook-creator#5]
Hi James,

First off thanks for this app! I was able to get this up and running on Heroku connected to a sandbox Salesforce instance. When creating a new webhook the app seems to be hitting Heroku's 30 second request limit. Is this something you have seen with your app? It seems to be timing out for me in the call to `ForceUtil.deployZip`. Is the perhaps a sandbox thing? Any tips for digging deeper?

**Comment by jamesward** [comment]
Thanks for the heads up on this.  Sometimes it does seem that the deployment takes a while and I haven't yet done anything in this app to deal with the 30 second timeout.  I'll add a workaround for this and let you know here once I've fixed it.

**Comment by jamesward** [comment]
Oh, actually this might be because this app doesn't yet support sandboxes. So once I fix #3 hopefully everything will work.

**Comment by jamesward** [comment]
@srbiv Can you give https://salesforce-webhook-creator.herokuapp.com/ a try and let me know how it goes this time?  I didn't workaround the 30 second timeout so this still might be an issue.

**Comment by srbiv** [comment]
I gave it a try. It seems like it is still hitting the 30 second timeout but it is hard to tell on my end. You should be able to verify with looking for H12 errors in the logs.

**Comment by jamesward** [comment]
This should be fixed by https://github.com/jamesward/salesforce-webhook-creator/commit/d7a3429b8494c1854e26d839555f0b05b59c85dd

But it would be great if you could give it a try and let me know how it goes.

**Comment by srbiv** [comment]
Thanks!

That seems to fix the timeout issue on Heroku's end. However, it still doesn't seem to be creating anything. After a bit of a wait the page ends up refreshing. I don't see anything out of the ordinary in Heroku's logs. I am still very new to Salesforce, can you make any suggestions as for where to look for errors on that end?

**Comment by jamesward** [comment]
Can you look in your Apex classes and see if anything was created?  Also check the deploy status.  Check:
https://login.salesforce.com/01p
https://login.salesforce.com/changemgmt/monitorDeployment.apexp

**Comment by srbiv** [comment]
I think I see these deployments queued up! Thanks.

**Comment by jamesward** [comment]
The page shouldn't refresh until the deployment has finished or failed...  But my timeouts might not be long enough.  Let me know if you get a completed deployment and how long it took.

**Comment by srbiv** [comment]
It looks like they are taking over an hour currently.

**Comment by jamesward** [comment]
Oh wow. It only takes mine a few seconds.  But that is probably because I don't have much in my org.  I wonder if it is the tests that are taking so long...  I could add a checkbox to turn them off.

**Comment by ceedon** [comment]
:+1: Would be useful for sandboxing.

**Comment by srbiv** [comment]
Yeah it looks like our instance has about 2776 tests to run. It takes quite a while in the sandbox.

**Comment by jamesward** [comment]
I've deployed a change that disables running all of the tests.  But I feel like the last time I tried this, deployment failed because none of the tests were run.  I've tried to just run the tests for the Trigger I'm deploying but that results in a Code Coverage error.  So give it a try again and lets see what happens.  Thanks!

**Comment by jamesward** [comment]
I've switched the code to a different way of doing deployment which should fix this.  Let me know if things still aren't working right.
